
import { SongItem } from './SongData';

const MusicList: SongItem[] = [
  { id: 1, title: '偷心', singer: '张婉植', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar1'), src: 'boisterous.wav', index:0},
  { id: 2, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar2'), src: 'dynamic.wav', index:1 },
  { id: 3, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar3'), src: 'dynamic.wav', index:2 },
  { id: 4, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar4'), src: 'boisterous.wav' , index:3},
  { id: 5, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar5'), src: 'dynamic.wav', index:4 },
  { id: 6, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar1'), src: 'boisterous.wav' , index:5},
  { id: 7, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar2'), src: 'dynamic.wav', index:6 },
  { id: 8, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar3'), src: 'boisterous.wav', index:7 },
  { id: 9, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar4'), src: 'dynamic.wav', index:8 },
  { id: 10, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar5'), src: 'boisterous.wav', index:9 },
  { id: 11, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar1'), src: 'dynamic.wav', index:10},
  { id: 12, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar2'), src: 'boisterous.wav', index:11 },
  { id: 13, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar3'), src: 'dynamic.wav', index:12 },
  { id: 14, title: '偷心', singer: '张学友', mark: $r('app.media.ic_sq'),
    label: $r('app.media.ic_avatar4'), src: 'boisterous.wav', index:13 },
  { id: 15, title: '偷心', singer: '张学友', mark: $r('app.media.ic_vip'),
    label: $r('app.media.ic_avatar5'), src: 'dynamic.wav', index:14 }
]

export { MusicList }